apiVersion: v1
kind: Namespace
metadata:
  name: alb-prod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: alb-prod
  name: cg-public-alb-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx-svc
              port:
                number: 80